# Generated by Django 3.1.3 on 2020-11-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebProj4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='created_at',
            new_name='time',
        ),
    ]
